server:
  port: 4040

spring:
  application:
    name: customer-service


  # database config
  datasource:
    url: jdbc:h2:mem:books_data
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  #  enabling the H2 console
  h2:
    console:
      enabled: true

